services:
  task-manager:
    build:
      context: ../02-run-app-using-compose/.
      labels:
        - org.superosystem.compose.app=task-manager
    image: task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - task-manager-public-network
      - redis-network
    labels:
      - org.superosystem.compose.app=task-manager

  redis:
    image: redis
    ports:
      - 6379:6379
    entrypoint: ["redis-server","/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - backup:/backup
    networks:
      - redis-network
    labels:
      - org.superosystem.compose.app=task-manager

  redis-backup:
    image: bash
    entrypoint: ["/snapshot-backup.sh"]
    depends_on:
      - redis
    environment:
      - BACKUP_PERIOD=10
    volumes:
      - ./snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro
      - backup:/backup
    networks:
      - task-manager-public-network
    labels:
      - org.superosystem.compose.app=task-manager

volumes:
  redis-data:
    labels:
      - org.superosystem.compose.app=task-manager
  backup:
    labels:
      - org.superosystem.compose.app=task-manager
      
networks:
  task-manager-public-network:
    labels:
      - org.superosystem.compose.app=task-manager
  redis-network:
    labels:
      - org.superosystem.compose.app=task-manager